name: Code Checks (Node.js)

on:
  workflow_call:
    inputs:
      pre_install_script:
        description: "Script to run before running `yarn install`"
        required: false
        type: string
        default: 'echo "No Pre-Install Script Provided"'
      post_install_script:
        description: "Script to run after running `yarn install`"
        required: false
        type: string
        default: 'echo "No Post-Install Script Provided"'
      post_checks_script:
        description: "Script to run after running all checks"
        required: false
        type: string
        default: 'echo "No Post-Checks Script Provided"'

jobs:
  code_checks:
    name: Code Checks (Next.js)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "yarn"

      # Cache TS and ESLint compilation states
      - name: Restore Lint & TS Cache
        uses: actions/cache@v6
        with:
          path: |
            .eslintcache
            *.tsbuildinfo
          key: ${{ runner.os }}-checks-compiler-${{ hashFiles('yarn.lock') }}-
          restore-keys: |
            ${{ runner.os }}-checks-compiler-${{ hashFiles('yarn.lock') }}-
            ${{ runner.os }}-checks-compiler-

      - name: Pre-Install Script
        run: ${{ inputs.pre_install_script }}

      # Install dependencies, bypass `npm prepare`
      - name: "`yarn install`"
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Post-Install Script
        run: ${{ inputs.post_install_script }}

      # Check TypeScript and eslint
      - name: TypeScript Check
        run: yarn check-typescript --incremental --tsBuildInfoFile tscheck.tsbuildinfo

      - name: eslint Check
        run: yarn check-eslint --cache --cache-location .eslintcache

      - name: Post-Checks Script
        run: ${{ inputs.post_checks_script }}
