name: Generate Timestamp Build ID

# This workflow products an `output` of `build_id`.
# The build_id format is "vYYYY-MM-DD-hhmmss"
#
# Use it like so:
#
# jobs:
#    make_build_id:
#     name: Make Build ID
#     uses: Jockey/reusable-workflows/.github/workflows/nextjs-code-checks.yml@master
#
#   use_build_id:
#     needs: [make_build_id]
#     steps:
#       - run: echo "${{ needs.make_build_id.outputs.build_id }}"
#

on:
  workflow_call:
    outputs:
      build_id: 
        description: "The Build ID, format of \"vYYYY-MM-DD-hhmmss\""
        value: ${{ jobs.build_id.outputs.build_id }}

permissions:
  pull-requests: write

jobs:
  build_id:
    name: Generate Build ID
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.make_id.outputs.build_id }}
    steps:
      - name: Generate Build Strings
        id: make_id
        run: |
          echo "build_id=$(date +'v%Y-%m-%d-%H%M%S')" >> $GITHUB_OUTPUT

  attach_to_pr:
    name: Attach Build ID to PR
    if: github.event_name == 'pull_request'
    needs: [build_id]
    uses: jupier/powerful-pr-comment@v0.0.5
    with:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      commentId: buildid-cmmt
      body: |
        Build ID for this Pull Request: ${{ needs.build_id.outputs.build_id }}
